delete from recarga;
ALTER TABLE recarga AUTO_INCREMENT = 1;
delete from recargamonedero;
ALTER TABLE recargamonedero AUTO_INCREMENT = 1;
delete from recargaprog;
ALTER TABLE recargaprog AUTO_INCREMENT = 1;
delete from saldomonedero;
ALTER TABLE saldomonedero AUTO_INCREMENT = 1;
delete from tarjeta;
ALTER TABLE tarjeta AUTO_INCREMENT = 1;
delete from usuario;
ALTER TABLE usuario AUTO_INCREMENT = 1;