//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.8689
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace MasTicket
{
	// 
	// This source code was auto-generated by xsd, Version=2.0.50727.3038.
	// 


	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class RiskInformation
	{

		private TransactionType transactionField;

		private BillingType billingField;

		private ShoppingCartItemsType shoppingCartItemsField;

		private CustomMerchantDataType customMerchantDataField;

		private RiskInformationVersion versionField;

		/// <comentarios/>
		public TransactionType Transaction
		{
			get
			{
				return this.transactionField;
			}
			set
			{
				this.transactionField = value;
			}
		}

		/// <comentarios/>
		public BillingType Billing
		{
			get
			{
				return this.billingField;
			}
			set
			{
				this.billingField = value;
			}
		}

		/// <comentarios/>
		public ShoppingCartItemsType ShoppingCartItems
		{
			get
			{
				return this.shoppingCartItemsField;
			}
			set
			{
				this.shoppingCartItemsField = value;
			}
		}

		/// <comentarios/>
		public CustomMerchantDataType CustomMerchantData
		{
			get
			{
				return this.customMerchantDataField;
			}
			set
			{
				this.customMerchantDataField = value;
			}
		}

		/// <comentarios/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public RiskInformationVersion version
		{
			get
			{
				return this.versionField;
			}
			set
			{
				this.versionField = value;
			}
		}
	}

	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class TransactionType
	{

		private bool isB2BTransactionField;

		private bool isOneTimePaymentField;

		private TransactionTypeAccount accountField;

		private TransactionTypeAuthentication authenticationField;

		private TransactionTypeChannel channelField;

		private PromotionType[] promotionField;

		private TransactionTypeMoneyTransfer moneyTransferField;

		private string timeStampField;

		/// <comentarios/>
		public bool IsB2BTransaction
		{
			get
			{
				return this.isB2BTransactionField;
			}
			set
			{
				this.isB2BTransactionField = value;
			}
		}

		/// <comentarios/>
		public bool IsOneTimePayment
		{
			get
			{
				return this.isOneTimePaymentField;
			}
			set
			{
				this.isOneTimePaymentField = value;
			}
		}

		/// <comentarios/>
		public TransactionTypeAccount Account
		{
			get
			{
				return this.accountField;
			}
			set
			{
				this.accountField = value;
			}
		}

		/// <comentarios/>
		public TransactionTypeAuthentication Authentication
		{
			get
			{
				return this.authenticationField;
			}
			set
			{
				this.authenticationField = value;
			}
		}

		/// <comentarios/>
		public TransactionTypeChannel Channel
		{
			get
			{
				return this.channelField;
			}
			set
			{
				this.channelField = value;
			}
		}

		/// <comentarios/>
		[System.Xml.Serialization.XmlElementAttribute("Promotion")]
		public PromotionType[] Promotion
		{
			get
			{
				return this.promotionField;
			}
			set
			{
				this.promotionField = value;
			}
		}

		/// <comentarios/>
		public TransactionTypeMoneyTransfer MoneyTransfer
		{
			get
			{
				return this.moneyTransferField;
			}
			set
			{
				this.moneyTransferField = value;
			}
		}

		/// <comentarios/>
		public string TimeStamp
		{
			get
			{
				return this.timeStampField;
			}
			set
			{
				this.timeStampField = value;
			}
		}
	}

	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class TransactionTypeAccount
	{

		private string accountIDField;

		private string loyaltyProgramIDField;

		private string emailField;

		private string mobilePhoneNumberField;

		private string workPhoneNumberField;

		private string createdDTMField;

		private string firstNameField;

		private string lastNameField;

		private AddressType[] addressField;

		private System.DateTime dOBField;

		private bool dOBFieldSpecified;

		private SocialNetworkType[] socialNetworkField;

		private bool hasNegativeHistoryField;

		/// <comentarios/>
		public string AccountID
		{
			get
			{
				return this.accountIDField;
			}
			set
			{
				this.accountIDField = value;
			}
		}

		/// <comentarios/>
		public string LoyaltyProgramID
		{
			get
			{
				return this.loyaltyProgramIDField;
			}
			set
			{
				this.loyaltyProgramIDField = value;
			}
		}

		/// <comentarios/>
		public string Email
		{
			get
			{
				return this.emailField;
			}
			set
			{
				this.emailField = value;
			}
		}

		/// <comentarios/>
		public string MobilePhoneNumber
		{
			get
			{
				return this.mobilePhoneNumberField;
			}
			set
			{
				this.mobilePhoneNumberField = value;
			}
		}

		/// <comentarios/>
		public string WorkPhoneNumber
		{
			get
			{
				return this.workPhoneNumberField;
			}
			set
			{
				this.workPhoneNumberField = value;
			}
		}

		/// <comentarios/>
		public string CreatedDTM
		{
			get
			{
				return this.createdDTMField;
			}
			set
			{
				this.createdDTMField = value; //.ToString("yyyy-MM-ddTHH:mm:ssZ");
			}
		}

		/// <comentarios/>
		public string FirstName
		{
			get
			{
				return this.firstNameField;
			}
			set
			{
				this.firstNameField = value;
			}
		}

		/// <comentarios/>
		public string LastName
		{
			get
			{
				return this.lastNameField;
			}
			set
			{
				this.lastNameField = value;
			}
		}

		/// <comentarios/>
		[System.Xml.Serialization.XmlElementAttribute("Address")]
		public AddressType[] Address
		{
			get
			{
				return this.addressField;
			}
			set
			{
				this.addressField = value;
			}
		}

		/// <comentarios/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
		public System.DateTime DOB
		{
			get
			{
				return this.dOBField;
			}
			set
			{
				this.dOBField = value;
			}
		}

		/// <comentarios/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool DOBSpecified
		{
			get
			{
				return this.dOBFieldSpecified;
			}
			set
			{
				this.dOBFieldSpecified = value;
			}
		}

		/// <comentarios/>
		[System.Xml.Serialization.XmlElementAttribute("SocialNetwork")]
		public SocialNetworkType[] SocialNetwork
		{
			get
			{
				return this.socialNetworkField;
			}
			set
			{
				this.socialNetworkField = value;
			}
		}

		/// <comentarios/>
		public bool HasNegativeHistory
		{
			get
			{
				return this.hasNegativeHistoryField;
			}
			set
			{
				this.hasNegativeHistoryField = value;
			}
		}
	}

	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class AddressType
	{

		private string addressLine1Field;

		private string addressLine2Field;

		private string cityField;

		private string stateField;

		private string postalCodeField;

		private string countryCodeField;

		/// <comentarios/>
		public string AddressLine1
		{
			get
			{
				return this.addressLine1Field;
			}
			set
			{
				this.addressLine1Field = value;
			}
		}

		/// <comentarios/>
		public string AddressLine2
		{
			get
			{
				return this.addressLine2Field;
			}
			set
			{
				this.addressLine2Field = value;
			}
		}

		/// <comentarios/>
		public string City
		{
			get
			{
				return this.cityField;
			}
			set
			{
				this.cityField = value;
			}
		}

		/// <comentarios/>
		public string State
		{
			get
			{
				return this.stateField;
			}
			set
			{
				this.stateField = value;
			}
		}

		/// <comentarios/>
		public string PostalCode
		{
			get
			{
				return this.postalCodeField;
			}
			set
			{
				this.postalCodeField = value;
			}
		}

		/// <comentarios/>
		public string CountryCode
		{
			get
			{
				return this.countryCodeField;
			}
			set
			{
				this.countryCodeField = value;
			}
		}
	}

	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class CustomMerchantDataType
	{

		private System.Xml.XmlElement[] anyField;

		/// <comentarios/>
		[System.Xml.Serialization.XmlAnyElementAttribute()]
		public System.Xml.XmlElement[] Any
		{
			get
			{
				return this.anyField;
			}
			set
			{
				this.anyField = value;
			}
		}
	}

	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class LineItemsType
	{

		private LineItemsTypeLineItem[] lineItemField;

		private string countField;

		/// <comentarios/>
		[System.Xml.Serialization.XmlElementAttribute("LineItem")]
		public LineItemsTypeLineItem[] LineItem
		{
			get
			{
				return this.lineItemField;
			}
			set
			{
				this.lineItemField = value;
			}
		}

		/// <comentarios/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "positiveInteger")]
		public string count
		{
			get
			{
				return this.countField;
			}
			set
			{
				this.countField = value;
			}
		}
	}

	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class LineItemsTypeLineItem
	{

		private string productCodeField;

		private string productDescriptionField;

		private decimal unitPriceField;

		private string quantityField;

		private PromotionType promotionField;

		/// <comentarios/>
		public string ProductCode
		{
			get
			{
				return this.productCodeField;
			}
			set
			{
				this.productCodeField = value;
			}
		}

		/// <comentarios/>
		public string ProductDescription
		{
			get
			{
				return this.productDescriptionField;
			}
			set
			{
				this.productDescriptionField = value;
			}
		}

		/// <comentarios/>
		public decimal UnitPrice
		{
			get
			{
				return this.unitPriceField;
			}
			set
			{
				this.unitPriceField = value;
			}
		}

		/// <comentarios/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
		public string Quantity
		{
			get
			{
				return this.quantityField;
			}
			set
			{
				this.quantityField = value;
			}
		}

		/// <comentarios/>
		public PromotionType Promotion
		{
			get
			{
				return this.promotionField;
			}
			set
			{
				this.promotionField = value;
			}
		}
	}

	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class PromotionType
	{

		private string codeField;

		private string descriptionField;

		private decimal discountField;

		/// <comentarios/>
		public string Code
		{
			get
			{
				return this.codeField;
			}
			set
			{
				this.codeField = value;
			}
		}

		/// <comentarios/>
		public string Description
		{
			get
			{
				return this.descriptionField;
			}
			set
			{
				this.descriptionField = value;
			}
		}

		/// <comentarios/>
		public decimal Discount
		{
			get
			{
				return this.discountField;
			}
			set
			{
				this.discountField = value;
			}
		}
	}

	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class ShoppingCartItemsType
	{

		private ShoppingCartItemsTypeShoppingCartItem[] shoppingCartItemField;

		private string countField;

		/// <comentarios/>
		[System.Xml.Serialization.XmlElementAttribute("ShoppingCartItem")]
		public ShoppingCartItemsTypeShoppingCartItem[] ShoppingCartItem
		{
			get
			{
				return this.shoppingCartItemField;
			}
			set
			{
				this.shoppingCartItemField = value;
			}
		}

		/// <comentarios/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "positiveInteger")]
		public string count
		{
			get
			{
				return this.countField;
			}
			set
			{
				this.countField = value;
			}
		}
	}

	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class ShoppingCartItemsTypeShoppingCartItem
	{

		private ShoppingCartItemsTypeShoppingCartItemDeliveryMethod deliveryMethodField;

		private ShoppingCartItemsTypeShoppingCartItemDeliveryRecipient deliveryRecipientField;

		private ShoppingCartItemsTypeShoppingCartItemFees feesField;

		private ShoppingCartItemsTypeShoppingCartItemGiftingMessage giftingMessageField;

		private LineItemsType lineItemsField;

		/// <comentarios/>
		public ShoppingCartItemsTypeShoppingCartItemDeliveryMethod DeliveryMethod
		{
			get
			{
				return this.deliveryMethodField;
			}
			set
			{
				this.deliveryMethodField = value;
			}
		}

		/// <comentarios/>
		public ShoppingCartItemsTypeShoppingCartItemDeliveryRecipient DeliveryRecipient
		{
			get
			{
				return this.deliveryRecipientField;
			}
			set
			{
				this.deliveryRecipientField = value;
			}
		}

		/// <comentarios/>
		public ShoppingCartItemsTypeShoppingCartItemFees Fees
		{
			get
			{
				return this.feesField;
			}
			set
			{
				this.feesField = value;
			}
		}

		/// <comentarios/>
		public ShoppingCartItemsTypeShoppingCartItemGiftingMessage GiftingMessage
		{
			get
			{
				return this.giftingMessageField;
			}
			set
			{
				this.giftingMessageField = value;
			}
		}

		/// <comentarios/>
		public LineItemsType LineItems
		{
			get
			{
				return this.lineItemsField;
			}
			set
			{
				this.lineItemsField = value;
			}
		}
	}

	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public enum ShoppingCartItemsTypeShoppingCartItemDeliveryMethod
	{

		/// <comentarios/>
		Email,

		/// <comentarios/>
		PhysicalShipping,

		/// <comentarios/>
		Reload,

		/// <comentarios/>
		DigitalDownload,

		/// <comentarios/>
		MoneyTransfer,

		/// <comentarios/>
		Other,
	}

	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class ShoppingCartItemsTypeShoppingCartItemDeliveryRecipient
	{

		private string companyField;

		private string accountIDField;

		private System.DateTime accountCreatedDateField;

		private bool accountCreatedDateFieldSpecified;

		private string firstNameField;

		private string lastNameField;

		private AddressType addressField;

		private string emailField;

		private string phoneNumberField;

		private string storedValueAccountIDField;

		/// <comentarios/>
		public string Company
		{
			get
			{
				return this.companyField;
			}
			set
			{
				this.companyField = value;
			}
		}

		/// <comentarios/>
		public string AccountID
		{
			get
			{
				return this.accountIDField;
			}
			set
			{
				this.accountIDField = value;
			}
		}

		/// <comentarios/>
		public System.DateTime AccountCreatedDate
		{
			get
			{
				return this.accountCreatedDateField;
			}
			set
			{
				this.accountCreatedDateField = value;
			}
		}

		/// <comentarios/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool AccountCreatedDateSpecified
		{
			get
			{
				return this.accountCreatedDateFieldSpecified;
			}
			set
			{
				this.accountCreatedDateFieldSpecified = value;
			}
		}

		/// <comentarios/>
		public string FirstName
		{
			get
			{
				return this.firstNameField;
			}
			set
			{
				this.firstNameField = value;
			}
		}

		/// <comentarios/>
		public string LastName
		{
			get
			{
				return this.lastNameField;
			}
			set
			{
				this.lastNameField = value;
			}
		}

		/// <comentarios/>
		public AddressType Address
		{
			get
			{
				return this.addressField;
			}
			set
			{
				this.addressField = value;
			}
		}

		/// <comentarios/>
		public string Email
		{
			get
			{
				return this.emailField;
			}
			set
			{
				this.emailField = value;
			}
		}

		/// <comentarios/>
		public string PhoneNumber
		{
			get
			{
				return this.phoneNumberField;
			}
			set
			{
				this.phoneNumberField = value;
			}
		}

		/// <comentarios/>
		public string StoredValueAccountID
		{
			get
			{
				return this.storedValueAccountIDField;
			}
			set
			{
				this.storedValueAccountIDField = value;
			}
		}
	}

	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class ShoppingCartItemsTypeShoppingCartItemFees
	{

		private ShoppingCartItemsTypeShoppingCartItemFeesFee[] feeField;

		private string countField;

		/// <comentarios/>
		[System.Xml.Serialization.XmlElementAttribute("Fee")]
		public ShoppingCartItemsTypeShoppingCartItemFeesFee[] Fee
		{
			get
			{
				return this.feeField;
			}
			set
			{
				this.feeField = value;
			}
		}

		/// <comentarios/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "positiveInteger")]
		public string count
		{
			get
			{
				return this.countField;
			}
			set
			{
				this.countField = value;
			}
		}
	}

	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class ShoppingCartItemsTypeShoppingCartItemFeesFee
	{

		private decimal amountField;

		private ShoppingCartItemsTypeShoppingCartItemFeesFeeFeeType[] feeTypeField;

		/// <comentarios/>
		public decimal Amount
		{
			get
			{
				return this.amountField;
			}
			set
			{
				this.amountField = value;
			}
		}

		/// <comentarios/>
		[System.Xml.Serialization.XmlElementAttribute("FeeType")]
		public ShoppingCartItemsTypeShoppingCartItemFeesFeeFeeType[] FeeType
		{
			get
			{
				return this.feeTypeField;
			}
			set
			{
				this.feeTypeField = value;
			}
		}
	}

	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public enum ShoppingCartItemsTypeShoppingCartItemFeesFeeFeeType
	{

		/// <comentarios/>
		ShippingCost,

		/// <comentarios/>
		MessageCost,

		/// <comentarios/>
		Other,
	}

	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class ShoppingCartItemsTypeShoppingCartItemGiftingMessage
	{

		private string fromField;

		private string toField;

		private string textField;

		/// <comentarios/>
		public string From
		{
			get
			{
				return this.fromField;
			}
			set
			{
				this.fromField = value;
			}
		}

		/// <comentarios/>
		public string To
		{
			get
			{
				return this.toField;
			}
			set
			{
				this.toField = value;
			}
		}

		/// <comentarios/>
		public string Text
		{
			get
			{
				return this.textField;
			}
			set
			{
				this.textField = value;
			}
		}
	}

	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class BillingType
	{

		private string emailField;

		private string contactPhoneNumberField;

		private string bankPhoneNumberField;

		private string paymentDeviceCreatedDtmField;

		private bool paymentDeviceCreatedDtmFieldSpecified;

		private System.DateTime paymentDeviceOwnerDOBField;

		private bool paymentDeviceOwnerDOBFieldSpecified;

		private bool hasNegativeHistoryField;

		/// <comentarios/>
		public string Email
		{
			get
			{
				return this.emailField;
			}
			set
			{
				this.emailField = value;
			}
		}

		/// <comentarios/>
		public string ContactPhoneNumber
		{
			get
			{
				return this.contactPhoneNumberField;
			}
			set
			{
				this.contactPhoneNumberField = value;
			}
		}

		/// <comentarios/>
		public string BankPhoneNumber
		{
			get
			{
				return this.bankPhoneNumberField;
			}
			set
			{
				this.bankPhoneNumberField = value;
			}
		}

		/// <comentarios/>
		public string PaymentDeviceCreatedDtm
		{
			get
			{
				return this.paymentDeviceCreatedDtmField;
			}
			set
			{
				this.paymentDeviceCreatedDtmField = value;
			}
		}

		/// <comentarios/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool PaymentDeviceCreatedDtmSpecified
		{
			get
			{
				return this.paymentDeviceCreatedDtmFieldSpecified;
			}
			set
			{
				this.paymentDeviceCreatedDtmFieldSpecified = value;
			}
		}

		/// <comentarios/>
		[System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
		public System.DateTime PaymentDeviceOwnerDOB
		{
			get
			{
				return this.paymentDeviceOwnerDOBField;
			}
			set
			{
				this.paymentDeviceOwnerDOBField = value;
			}
		}

		/// <comentarios/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool PaymentDeviceOwnerDOBSpecified
		{
			get
			{
				return this.paymentDeviceOwnerDOBFieldSpecified;
			}
			set
			{
				this.paymentDeviceOwnerDOBFieldSpecified = value;
			}
		}

		/// <comentarios/>
		public bool HasNegativeHistory
		{
			get
			{
				return this.hasNegativeHistoryField;
			}
			set
			{
				this.hasNegativeHistoryField = value;
			}
		}
	}

	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class SocialNetworkType
	{

		private SocialNetworkTypePlatform platformField;

		private string accountIDField;

		private string accountEmailField;

		/// <comentarios/>
		public SocialNetworkTypePlatform Platform
		{
			get
			{
				return this.platformField;
			}
			set
			{
				this.platformField = value;
			}
		}

		/// <comentarios/>
		public string AccountID
		{
			get
			{
				return this.accountIDField;
			}
			set
			{
				this.accountIDField = value;
			}
		}

		/// <comentarios/>
		public string AccountEmail
		{
			get
			{
				return this.accountEmailField;
			}
			set
			{
				this.accountEmailField = value;
			}
		}
	}

	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public enum SocialNetworkTypePlatform
	{

		/// <comentarios/>
		Facebook,

		/// <comentarios/>
		GooglePlus,

		/// <comentarios/>
		Twitter,

		/// <comentarios/>
		Other,
	}

	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class TransactionTypeAuthentication
	{

		private bool isAuthenticatedField;

		private TransactionTypeAuthenticationAuthenticationMethod authenticationMethodField;
		//private string authenticationMethodField;

		private bool authenticationMethodFieldSpecified;

		private string loginIDField;

		private SocialNetworkType socialNetworkField;

		/// <comentarios/>
		public bool IsAuthenticated
		{
			get
			{
				return this.isAuthenticatedField;
			}
			set
			{
				this.isAuthenticatedField = value;
			}
		}

		/// <comentarios/>
		public TransactionTypeAuthenticationAuthenticationMethod AuthenticationMethod
		//public string AuthenticationMethod
		{
			get
			{
				return this.authenticationMethodField;
			}
			set
			{
				this.authenticationMethodField = value;
			}
		}

		/// <comentarios/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool AuthenticationMethodSpecified
		{
			get
			{
				return this.authenticationMethodFieldSpecified;
			}
			set
			{
				this.authenticationMethodFieldSpecified = value;
			}
		}

		/// <comentarios/>
		public string LoginID
		{
			get
			{
				return this.loginIDField;
			}
			set
			{
				this.loginIDField = value;
			}
		}

		/// <comentarios/>
		public SocialNetworkType SocialNetwork
		{
			get
			{
				return this.socialNetworkField;
			}
			set
			{
				this.socialNetworkField = value;
			}
		}
	}

	/// <comentarios/>
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public enum TransactionTypeAuthenticationAuthenticationMethod
	{

		/// <comentarios/>
		Password,

		/// <comentarios/>
		PIN,


		/// <comentarios/>
		OAuth,

		/// <comentarios/>
		Other,
	}

	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class TransactionTypeChannel
	{

		private TransactionTypeChannelChannelCode channelCodeField;

		private string aNIField;

		private string iPAddressField;

		/// <comentarios/>
		public TransactionTypeChannelChannelCode ChannelCode
		{
			get
			{
				return this.channelCodeField;
			}
			set
			{
				this.channelCodeField = value;
			}
		}

		/// <comentarios/>
		public string ANI
		{
			get
			{
				return this.aNIField;
			}
			set
			{
				this.aNIField = value;
			}
		}

		/// <comentarios/>
		public string IPAddress
		{
			get
			{
				return this.iPAddressField;
			}
			set
			{
				this.iPAddressField = value;
			}
		}
	}

	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public enum TransactionTypeChannelChannelCode
	{

		/// <comentarios/>
		Web,

		/// <comentarios/>
		IVR,

		/// <comentarios/>
		Store,

		/// <comentarios/>
		Mobile,

		/// <comentarios/>
		SMS,

		/// <comentarios/>
		Other,
	}

	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class TransactionTypeMoneyTransfer
	{

		private decimal exchangeRateField;

		private bool exchangeRateFieldSpecified;

		private decimal sendAmountField;

		private string sendCurrencyField;

		private decimal receiveAmountField;

		private string receiveCurrencyField;

		private TransactionTypeMoneyTransferPayout payoutField;

		/// <comentarios/>
		public decimal ExchangeRate
		{
			get
			{
				return this.exchangeRateField;
			}
			set
			{
				this.exchangeRateField = value;
			}
		}

		/// <comentarios/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool ExchangeRateSpecified
		{
			get
			{
				return this.exchangeRateFieldSpecified;
			}
			set
			{
				this.exchangeRateFieldSpecified = value;
			}
		}

		/// <comentarios/>
		public decimal SendAmount
		{
			get
			{
				return this.sendAmountField;
			}
			set
			{
				this.sendAmountField = value;
			}
		}

		/// <comentarios/>
		public string SendCurrency
		{
			get
			{
				return this.sendCurrencyField;
			}
			set
			{
				this.sendCurrencyField = value;
			}
		}

		/// <comentarios/>
		public decimal ReceiveAmount
		{
			get
			{
				return this.receiveAmountField;
			}
			set
			{
				this.receiveAmountField = value;
			}
		}

		/// <comentarios/>
		public string ReceiveCurrency
		{
			get
			{
				return this.receiveCurrencyField;
			}
			set
			{
				this.receiveCurrencyField = value;
			}
		}

		/// <comentarios/>
		public TransactionTypeMoneyTransferPayout Payout
		{
			get
			{
				return this.payoutField;
			}
			set
			{
				this.payoutField = value;
			}
		}
	}

	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class TransactionTypeMoneyTransferPayout
	{

		private string countryField;

		private string stateField;

		private string cityField;

		private string postalCodeField;

		/// <comentarios/>
		public string Country
		{
			get
			{
				return this.countryField;
			}
			set
			{
				this.countryField = value;
			}
		}

		/// <comentarios/>
		public string State
		{
			get
			{
				return this.stateField;
			}
			set
			{
				this.stateField = value;
			}
		}

		/// <comentarios/>
		public string City
		{
			get
			{
				return this.cityField;
			}
			set
			{
				this.cityField = value;
			}
		}

		/// <comentarios/>
		public string PostalCode
		{
			get
			{
				return this.postalCodeField;
			}
			set
			{
				this.postalCodeField = value;
			}
		}
	}

	/// <comentarios/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public enum RiskInformationVersion
	{

		/// <comentarios/>
		[System.Xml.Serialization.XmlEnumAttribute("1.0")]
		Item10,

		/// <comentarios/>
		[System.Xml.Serialization.XmlEnumAttribute("1.2")]
		Item12,

		/// <comentarios/>
		[System.Xml.Serialization.XmlEnumAttribute("1.4")]
		Item14,

		/// <comentarios/>
		[System.Xml.Serialization.XmlEnumAttribute("1.5")]
		Item15,
	}
}
