//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace conAC.wsac {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Recarga", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(conAC.wsac.RecargaProg))]
    public partial class Recarga : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idrecargaField;
        
        private int idpaisField;
        
        private int idoperadoraField;
        
        private int idpaqueteField;
        
        private int idformapagoField;
        
        private int idtarjetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numerorecargaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contactorecargaField;
        
        private System.DateTime fechaField;
        
        private int errField;
        
        private int errVsField;
        
        private int errRsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentIDField;
        
        private int idusuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string osField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errvestadetalladoField;
        
        private bool esprogramadaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idrecarga {
            get {
                return this.idrecargaField;
            }
            set {
                if ((this.idrecargaField.Equals(value) != true)) {
                    this.idrecargaField = value;
                    this.RaisePropertyChanged("idrecarga");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int idpais {
            get {
                return this.idpaisField;
            }
            set {
                if ((this.idpaisField.Equals(value) != true)) {
                    this.idpaisField = value;
                    this.RaisePropertyChanged("idpais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int idoperadora {
            get {
                return this.idoperadoraField;
            }
            set {
                if ((this.idoperadoraField.Equals(value) != true)) {
                    this.idoperadoraField = value;
                    this.RaisePropertyChanged("idoperadora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int idpaquete {
            get {
                return this.idpaqueteField;
            }
            set {
                if ((this.idpaqueteField.Equals(value) != true)) {
                    this.idpaqueteField = value;
                    this.RaisePropertyChanged("idpaquete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int idformapago {
            get {
                return this.idformapagoField;
            }
            set {
                if ((this.idformapagoField.Equals(value) != true)) {
                    this.idformapagoField = value;
                    this.RaisePropertyChanged("idformapago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int idtarjeta {
            get {
                return this.idtarjetaField;
            }
            set {
                if ((this.idtarjetaField.Equals(value) != true)) {
                    this.idtarjetaField = value;
                    this.RaisePropertyChanged("idtarjeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string numerorecarga {
            get {
                return this.numerorecargaField;
            }
            set {
                if ((object.ReferenceEquals(this.numerorecargaField, value) != true)) {
                    this.numerorecargaField = value;
                    this.RaisePropertyChanged("numerorecarga");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string contactorecarga {
            get {
                return this.contactorecargaField;
            }
            set {
                if ((object.ReferenceEquals(this.contactorecargaField, value) != true)) {
                    this.contactorecargaField = value;
                    this.RaisePropertyChanged("contactorecarga");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((this.fechaField.Equals(value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int err {
            get {
                return this.errField;
            }
            set {
                if ((this.errField.Equals(value) != true)) {
                    this.errField = value;
                    this.RaisePropertyChanged("err");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int errVs {
            get {
                return this.errVsField;
            }
            set {
                if ((this.errVsField.Equals(value) != true)) {
                    this.errVsField = value;
                    this.RaisePropertyChanged("errVs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public int errRs {
            get {
                return this.errRsField;
            }
            set {
                if ((this.errRsField.Equals(value) != true)) {
                    this.errRsField = value;
                    this.RaisePropertyChanged("errRs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string TransactionID {
            get {
                return this.TransactionIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionIDField, value) != true)) {
                    this.TransactionIDField = value;
                    this.RaisePropertyChanged("TransactionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string PaymentID {
            get {
                return this.PaymentIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentIDField, value) != true)) {
                    this.PaymentIDField = value;
                    this.RaisePropertyChanged("PaymentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public int idusuario {
            get {
                return this.idusuarioField;
            }
            set {
                if ((this.idusuarioField.Equals(value) != true)) {
                    this.idusuarioField = value;
                    this.RaisePropertyChanged("idusuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string ip {
            get {
                return this.ipField;
            }
            set {
                if ((object.ReferenceEquals(this.ipField, value) != true)) {
                    this.ipField = value;
                    this.RaisePropertyChanged("ip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string os {
            get {
                return this.osField;
            }
            set {
                if ((object.ReferenceEquals(this.osField, value) != true)) {
                    this.osField = value;
                    this.RaisePropertyChanged("os");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string errvestadetallado {
            get {
                return this.errvestadetalladoField;
            }
            set {
                if ((object.ReferenceEquals(this.errvestadetalladoField, value) != true)) {
                    this.errvestadetalladoField = value;
                    this.RaisePropertyChanged("errvestadetallado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public bool esprogramada {
            get {
                return this.esprogramadaField;
            }
            set {
                if ((this.esprogramadaField.Equals(value) != true)) {
                    this.esprogramadaField = value;
                    this.RaisePropertyChanged("esprogramada");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecargaProg", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RecargaProg : conAC.wsac.Recarga {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string diasmesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string diasmes {
            get {
                return this.diasmesField;
            }
            set {
                if ((object.ReferenceEquals(this.diasmesField, value) != true)) {
                    this.diasmesField = value;
                    this.RaisePropertyChanged("diasmes");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecargaMonedero", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RecargaMonedero : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idrecargamonederoField;
        
        private int idtarjetaField;
        
        private decimal montoField;
        
        private System.DateTime fechaField;
        
        private int errField;
        
        private int errVsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentIDField;
        
        private int idusuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string osField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idrecargamonedero {
            get {
                return this.idrecargamonederoField;
            }
            set {
                if ((this.idrecargamonederoField.Equals(value) != true)) {
                    this.idrecargamonederoField = value;
                    this.RaisePropertyChanged("idrecargamonedero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idtarjeta {
            get {
                return this.idtarjetaField;
            }
            set {
                if ((this.idtarjetaField.Equals(value) != true)) {
                    this.idtarjetaField = value;
                    this.RaisePropertyChanged("idtarjeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal monto {
            get {
                return this.montoField;
            }
            set {
                if ((this.montoField.Equals(value) != true)) {
                    this.montoField = value;
                    this.RaisePropertyChanged("monto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((this.fechaField.Equals(value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int err {
            get {
                return this.errField;
            }
            set {
                if ((this.errField.Equals(value) != true)) {
                    this.errField = value;
                    this.RaisePropertyChanged("err");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int errVs {
            get {
                return this.errVsField;
            }
            set {
                if ((this.errVsField.Equals(value) != true)) {
                    this.errVsField = value;
                    this.RaisePropertyChanged("errVs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string TransactionID {
            get {
                return this.TransactionIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionIDField, value) != true)) {
                    this.TransactionIDField = value;
                    this.RaisePropertyChanged("TransactionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string PaymentID {
            get {
                return this.PaymentIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentIDField, value) != true)) {
                    this.PaymentIDField = value;
                    this.RaisePropertyChanged("PaymentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int idusuario {
            get {
                return this.idusuarioField;
            }
            set {
                if ((this.idusuarioField.Equals(value) != true)) {
                    this.idusuarioField = value;
                    this.RaisePropertyChanged("idusuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string ip {
            get {
                return this.ipField;
            }
            set {
                if ((object.ReferenceEquals(this.ipField, value) != true)) {
                    this.ipField = value;
                    this.RaisePropertyChanged("ip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string os {
            get {
                return this.osField;
            }
            set {
                if ((object.ReferenceEquals(this.osField, value) != true)) {
                    this.osField = value;
                    this.RaisePropertyChanged("os");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idusuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numerocontactoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string first_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string last_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string genderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pictureField;
        
        private bool registradoField;
        
        private int idpaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nipField;
        
        private System.DateTime fechaaltaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idusuario {
            get {
                return this.idusuarioField;
            }
            set {
                if ((this.idusuarioField.Equals(value) != true)) {
                    this.idusuarioField = value;
                    this.RaisePropertyChanged("idusuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string numerocontacto {
            get {
                return this.numerocontactoField;
            }
            set {
                if ((object.ReferenceEquals(this.numerocontactoField, value) != true)) {
                    this.numerocontactoField = value;
                    this.RaisePropertyChanged("numerocontacto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string first_name {
            get {
                return this.first_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.first_nameField, value) != true)) {
                    this.first_nameField = value;
                    this.RaisePropertyChanged("first_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string last_name {
            get {
                return this.last_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.last_nameField, value) != true)) {
                    this.last_nameField = value;
                    this.RaisePropertyChanged("last_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string gender {
            get {
                return this.genderField;
            }
            set {
                if ((object.ReferenceEquals(this.genderField, value) != true)) {
                    this.genderField = value;
                    this.RaisePropertyChanged("gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string picture {
            get {
                return this.pictureField;
            }
            set {
                if ((object.ReferenceEquals(this.pictureField, value) != true)) {
                    this.pictureField = value;
                    this.RaisePropertyChanged("picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public bool registrado {
            get {
                return this.registradoField;
            }
            set {
                if ((this.registradoField.Equals(value) != true)) {
                    this.registradoField = value;
                    this.RaisePropertyChanged("registrado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int idpais {
            get {
                return this.idpaisField;
            }
            set {
                if ((this.idpaisField.Equals(value) != true)) {
                    this.idpaisField = value;
                    this.RaisePropertyChanged("idpais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string nip {
            get {
                return this.nipField;
            }
            set {
                if ((object.ReferenceEquals(this.nipField, value) != true)) {
                    this.nipField = value;
                    this.RaisePropertyChanged("nip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.DateTime fechaalta {
            get {
                return this.fechaaltaField;
            }
            set {
                if ((this.fechaaltaField.Equals(value) != true)) {
                    this.fechaaltaField = value;
                    this.RaisePropertyChanged("fechaalta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tarjeta", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Tarjeta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idtarjetaField;
        
        private int idpaisField;
        
        private int idemisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string permtokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Last4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titularFNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titularLNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string calleynumeroField;
        
        private int idciudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigopostalField;
        
        private int idestadoField;
        
        private int idusuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string expirationMMYYField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idtarjeta {
            get {
                return this.idtarjetaField;
            }
            set {
                if ((this.idtarjetaField.Equals(value) != true)) {
                    this.idtarjetaField = value;
                    this.RaisePropertyChanged("idtarjeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int idpais {
            get {
                return this.idpaisField;
            }
            set {
                if ((this.idpaisField.Equals(value) != true)) {
                    this.idpaisField = value;
                    this.RaisePropertyChanged("idpais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int idemisor {
            get {
                return this.idemisorField;
            }
            set {
                if ((this.idemisorField.Equals(value) != true)) {
                    this.idemisorField = value;
                    this.RaisePropertyChanged("idemisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string permtoken {
            get {
                return this.permtokenField;
            }
            set {
                if ((object.ReferenceEquals(this.permtokenField, value) != true)) {
                    this.permtokenField = value;
                    this.RaisePropertyChanged("permtoken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Last4 {
            get {
                return this.Last4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Last4Field, value) != true)) {
                    this.Last4Field = value;
                    this.RaisePropertyChanged("Last4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string titularFN {
            get {
                return this.titularFNField;
            }
            set {
                if ((object.ReferenceEquals(this.titularFNField, value) != true)) {
                    this.titularFNField = value;
                    this.RaisePropertyChanged("titularFN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string titularLN {
            get {
                return this.titularLNField;
            }
            set {
                if ((object.ReferenceEquals(this.titularLNField, value) != true)) {
                    this.titularLNField = value;
                    this.RaisePropertyChanged("titularLN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string calleynumero {
            get {
                return this.calleynumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.calleynumeroField, value) != true)) {
                    this.calleynumeroField = value;
                    this.RaisePropertyChanged("calleynumero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int idciudad {
            get {
                return this.idciudadField;
            }
            set {
                if ((this.idciudadField.Equals(value) != true)) {
                    this.idciudadField = value;
                    this.RaisePropertyChanged("idciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string codigopostal {
            get {
                return this.codigopostalField;
            }
            set {
                if ((object.ReferenceEquals(this.codigopostalField, value) != true)) {
                    this.codigopostalField = value;
                    this.RaisePropertyChanged("codigopostal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int idestado {
            get {
                return this.idestadoField;
            }
            set {
                if ((this.idestadoField.Equals(value) != true)) {
                    this.idestadoField = value;
                    this.RaisePropertyChanged("idestado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public int idusuario {
            get {
                return this.idusuarioField;
            }
            set {
                if ((this.idusuarioField.Equals(value) != true)) {
                    this.idusuarioField = value;
                    this.RaisePropertyChanged("idusuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string expirationMMYY {
            get {
                return this.expirationMMYYField;
            }
            set {
                if ((object.ReferenceEquals(this.expirationMMYYField, value) != true)) {
                    this.expirationMMYYField = value;
                    this.RaisePropertyChanged("expirationMMYY");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsac.Isac")]
    public interface Isac {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento where del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Isac/GetCatalogo", ReplyAction="http://tempuri.org/Isac/GetCatalogoResponse")]
        conAC.wsac.GetCatalogoResponse GetCatalogo(conAC.wsac.GetCatalogoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Isac/GetCatalogo", ReplyAction="http://tempuri.org/Isac/GetCatalogoResponse")]
        System.Threading.Tasks.Task<conAC.wsac.GetCatalogoResponse> GetCatalogoAsync(conAC.wsac.GetCatalogoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Isac/EnviaMailRecordatorio", ReplyAction="http://tempuri.org/Isac/EnviaMailRecordatorioResponse")]
        void EnviaMailRecordatorio(int idusuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Isac/EnviaMailRecordatorio", ReplyAction="http://tempuri.org/Isac/EnviaMailRecordatorioResponse")]
        System.Threading.Tasks.Task EnviaMailRecordatorioAsync(int idusuario);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento r del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Isac/AltaRecargaProg", ReplyAction="http://tempuri.org/Isac/AltaRecargaProgResponse")]
        conAC.wsac.AltaRecargaProgResponse AltaRecargaProg(conAC.wsac.AltaRecargaProgRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Isac/AltaRecargaProg", ReplyAction="http://tempuri.org/Isac/AltaRecargaProgResponse")]
        System.Threading.Tasks.Task<conAC.wsac.AltaRecargaProgResponse> AltaRecargaProgAsync(conAC.wsac.AltaRecargaProgRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento r del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Isac/AltaRecarga", ReplyAction="http://tempuri.org/Isac/AltaRecargaResponse")]
        conAC.wsac.AltaRecargaResponse AltaRecarga(conAC.wsac.AltaRecargaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Isac/AltaRecarga", ReplyAction="http://tempuri.org/Isac/AltaRecargaResponse")]
        System.Threading.Tasks.Task<conAC.wsac.AltaRecargaResponse> AltaRecargaAsync(conAC.wsac.AltaRecargaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento r del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Isac/AltaRecargaMonedero", ReplyAction="http://tempuri.org/Isac/AltaRecargaMonederoResponse")]
        conAC.wsac.AltaRecargaMonederoResponse AltaRecargaMonedero(conAC.wsac.AltaRecargaMonederoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Isac/AltaRecargaMonedero", ReplyAction="http://tempuri.org/Isac/AltaRecargaMonederoResponse")]
        System.Threading.Tasks.Task<conAC.wsac.AltaRecargaMonederoResponse> AltaRecargaMonederoAsync(conAC.wsac.AltaRecargaMonederoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento r del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Isac/AltaRecargaViaWallet", ReplyAction="http://tempuri.org/Isac/AltaRecargaViaWalletResponse")]
        conAC.wsac.AltaRecargaViaWalletResponse AltaRecargaViaWallet(conAC.wsac.AltaRecargaViaWalletRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Isac/AltaRecargaViaWallet", ReplyAction="http://tempuri.org/Isac/AltaRecargaViaWalletResponse")]
        System.Threading.Tasks.Task<conAC.wsac.AltaRecargaViaWalletResponse> AltaRecargaViaWalletAsync(conAC.wsac.AltaRecargaViaWalletRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento u del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Isac/AltaUsr", ReplyAction="http://tempuri.org/Isac/AltaUsrResponse")]
        conAC.wsac.AltaUsrResponse AltaUsr(conAC.wsac.AltaUsrRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Isac/AltaUsr", ReplyAction="http://tempuri.org/Isac/AltaUsrResponse")]
        System.Threading.Tasks.Task<conAC.wsac.AltaUsrResponse> AltaUsrAsync(conAC.wsac.AltaUsrRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento u del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Isac/Mod_Usuario", ReplyAction="http://tempuri.org/Isac/Mod_UsuarioResponse")]
        conAC.wsac.Mod_UsuarioResponse Mod_Usuario(conAC.wsac.Mod_UsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Isac/Mod_Usuario", ReplyAction="http://tempuri.org/Isac/Mod_UsuarioResponse")]
        System.Threading.Tasks.Task<conAC.wsac.Mod_UsuarioResponse> Mod_UsuarioAsync(conAC.wsac.Mod_UsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Isac/EliminaTarjeta", ReplyAction="http://tempuri.org/Isac/EliminaTarjetaResponse")]
        bool EliminaTarjeta(int idtarjeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Isac/EliminaTarjeta", ReplyAction="http://tempuri.org/Isac/EliminaTarjetaResponse")]
        System.Threading.Tasks.Task<bool> EliminaTarjetaAsync(int idtarjeta);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento r del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Isac/CargaVesta1aVez", ReplyAction="http://tempuri.org/Isac/CargaVesta1aVezResponse")]
        conAC.wsac.CargaVesta1aVezResponse CargaVesta1aVez(conAC.wsac.CargaVesta1aVezRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Isac/CargaVesta1aVez", ReplyAction="http://tempuri.org/Isac/CargaVesta1aVezResponse")]
        System.Threading.Tasks.Task<conAC.wsac.CargaVesta1aVezResponse> CargaVesta1aVezAsync(conAC.wsac.CargaVesta1aVezRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento r del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Isac/CargaVesta2aVez", ReplyAction="http://tempuri.org/Isac/CargaVesta2aVezResponse")]
        conAC.wsac.CargaVesta2aVezResponse CargaVesta2aVez(conAC.wsac.CargaVesta2aVezRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Isac/CargaVesta2aVez", ReplyAction="http://tempuri.org/Isac/CargaVesta2aVezResponse")]
        System.Threading.Tasks.Task<conAC.wsac.CargaVesta2aVezResponse> CargaVesta2aVezAsync(conAC.wsac.CargaVesta2aVezRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCatalogoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCatalogo", Namespace="http://tempuri.org/", Order=0)]
        public conAC.wsac.GetCatalogoRequestBody Body;
        
        public GetCatalogoRequest() {
        }
        
        public GetCatalogoRequest(conAC.wsac.GetCatalogoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCatalogoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idcatalogo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string where;
        
        public GetCatalogoRequestBody() {
        }
        
        public GetCatalogoRequestBody(int idcatalogo, string where) {
            this.idcatalogo = idcatalogo;
            this.where = where;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCatalogoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCatalogoResponse", Namespace="http://tempuri.org/", Order=0)]
        public conAC.wsac.GetCatalogoResponseBody Body;
        
        public GetCatalogoResponse() {
        }
        
        public GetCatalogoResponse(conAC.wsac.GetCatalogoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCatalogoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCatalogoResult;
        
        public GetCatalogoResponseBody() {
        }
        
        public GetCatalogoResponseBody(string GetCatalogoResult) {
            this.GetCatalogoResult = GetCatalogoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AltaRecargaProgRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AltaRecargaProg", Namespace="http://tempuri.org/", Order=0)]
        public conAC.wsac.AltaRecargaProgRequestBody Body;
        
        public AltaRecargaProgRequest() {
        }
        
        public AltaRecargaProgRequest(conAC.wsac.AltaRecargaProgRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AltaRecargaProgRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public conAC.wsac.RecargaProg r;
        
        public AltaRecargaProgRequestBody() {
        }
        
        public AltaRecargaProgRequestBody(conAC.wsac.RecargaProg r) {
            this.r = r;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AltaRecargaProgResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AltaRecargaProgResponse", Namespace="http://tempuri.org/", Order=0)]
        public conAC.wsac.AltaRecargaProgResponseBody Body;
        
        public AltaRecargaProgResponse() {
        }
        
        public AltaRecargaProgResponse(conAC.wsac.AltaRecargaProgResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AltaRecargaProgResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AltaRecargaProgResult;
        
        public AltaRecargaProgResponseBody() {
        }
        
        public AltaRecargaProgResponseBody(int AltaRecargaProgResult) {
            this.AltaRecargaProgResult = AltaRecargaProgResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AltaRecargaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AltaRecarga", Namespace="http://tempuri.org/", Order=0)]
        public conAC.wsac.AltaRecargaRequestBody Body;
        
        public AltaRecargaRequest() {
        }
        
        public AltaRecargaRequest(conAC.wsac.AltaRecargaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AltaRecargaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public conAC.wsac.Recarga r;
        
        public AltaRecargaRequestBody() {
        }
        
        public AltaRecargaRequestBody(conAC.wsac.Recarga r) {
            this.r = r;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AltaRecargaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AltaRecargaResponse", Namespace="http://tempuri.org/", Order=0)]
        public conAC.wsac.AltaRecargaResponseBody Body;
        
        public AltaRecargaResponse() {
        }
        
        public AltaRecargaResponse(conAC.wsac.AltaRecargaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AltaRecargaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AltaRecargaResult;
        
        public AltaRecargaResponseBody() {
        }
        
        public AltaRecargaResponseBody(string AltaRecargaResult) {
            this.AltaRecargaResult = AltaRecargaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AltaRecargaMonederoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AltaRecargaMonedero", Namespace="http://tempuri.org/", Order=0)]
        public conAC.wsac.AltaRecargaMonederoRequestBody Body;
        
        public AltaRecargaMonederoRequest() {
        }
        
        public AltaRecargaMonederoRequest(conAC.wsac.AltaRecargaMonederoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AltaRecargaMonederoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public conAC.wsac.RecargaMonedero r;
        
        public AltaRecargaMonederoRequestBody() {
        }
        
        public AltaRecargaMonederoRequestBody(conAC.wsac.RecargaMonedero r) {
            this.r = r;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AltaRecargaMonederoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AltaRecargaMonederoResponse", Namespace="http://tempuri.org/", Order=0)]
        public conAC.wsac.AltaRecargaMonederoResponseBody Body;
        
        public AltaRecargaMonederoResponse() {
        }
        
        public AltaRecargaMonederoResponse(conAC.wsac.AltaRecargaMonederoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AltaRecargaMonederoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AltaRecargaMonederoResult;
        
        public AltaRecargaMonederoResponseBody() {
        }
        
        public AltaRecargaMonederoResponseBody(string AltaRecargaMonederoResult) {
            this.AltaRecargaMonederoResult = AltaRecargaMonederoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AltaRecargaViaWalletRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AltaRecargaViaWallet", Namespace="http://tempuri.org/", Order=0)]
        public conAC.wsac.AltaRecargaViaWalletRequestBody Body;
        
        public AltaRecargaViaWalletRequest() {
        }
        
        public AltaRecargaViaWalletRequest(conAC.wsac.AltaRecargaViaWalletRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AltaRecargaViaWalletRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public conAC.wsac.Recarga r;
        
        public AltaRecargaViaWalletRequestBody() {
        }
        
        public AltaRecargaViaWalletRequestBody(conAC.wsac.Recarga r) {
            this.r = r;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AltaRecargaViaWalletResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AltaRecargaViaWalletResponse", Namespace="http://tempuri.org/", Order=0)]
        public conAC.wsac.AltaRecargaViaWalletResponseBody Body;
        
        public AltaRecargaViaWalletResponse() {
        }
        
        public AltaRecargaViaWalletResponse(conAC.wsac.AltaRecargaViaWalletResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AltaRecargaViaWalletResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AltaRecargaViaWalletResult;
        
        public AltaRecargaViaWalletResponseBody() {
        }
        
        public AltaRecargaViaWalletResponseBody(string AltaRecargaViaWalletResult) {
            this.AltaRecargaViaWalletResult = AltaRecargaViaWalletResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AltaUsrRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AltaUsr", Namespace="http://tempuri.org/", Order=0)]
        public conAC.wsac.AltaUsrRequestBody Body;
        
        public AltaUsrRequest() {
        }
        
        public AltaUsrRequest(conAC.wsac.AltaUsrRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AltaUsrRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public conAC.wsac.Usuario u;
        
        public AltaUsrRequestBody() {
        }
        
        public AltaUsrRequestBody(conAC.wsac.Usuario u) {
            this.u = u;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AltaUsrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AltaUsrResponse", Namespace="http://tempuri.org/", Order=0)]
        public conAC.wsac.AltaUsrResponseBody Body;
        
        public AltaUsrResponse() {
        }
        
        public AltaUsrResponse(conAC.wsac.AltaUsrResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AltaUsrResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AltaUsrResult;
        
        public AltaUsrResponseBody() {
        }
        
        public AltaUsrResponseBody(int AltaUsrResult) {
            this.AltaUsrResult = AltaUsrResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Mod_UsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Mod_Usuario", Namespace="http://tempuri.org/", Order=0)]
        public conAC.wsac.Mod_UsuarioRequestBody Body;
        
        public Mod_UsuarioRequest() {
        }
        
        public Mod_UsuarioRequest(conAC.wsac.Mod_UsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Mod_UsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public conAC.wsac.Usuario u;
        
        public Mod_UsuarioRequestBody() {
        }
        
        public Mod_UsuarioRequestBody(conAC.wsac.Usuario u) {
            this.u = u;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Mod_UsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Mod_UsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public conAC.wsac.Mod_UsuarioResponseBody Body;
        
        public Mod_UsuarioResponse() {
        }
        
        public Mod_UsuarioResponse(conAC.wsac.Mod_UsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Mod_UsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Mod_UsuarioResult;
        
        public Mod_UsuarioResponseBody() {
        }
        
        public Mod_UsuarioResponseBody(int Mod_UsuarioResult) {
            this.Mod_UsuarioResult = Mod_UsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CargaVesta1aVezRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CargaVesta1aVez", Namespace="http://tempuri.org/", Order=0)]
        public conAC.wsac.CargaVesta1aVezRequestBody Body;
        
        public CargaVesta1aVezRequest() {
        }
        
        public CargaVesta1aVezRequest(conAC.wsac.CargaVesta1aVezRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CargaVesta1aVezRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public conAC.wsac.Recarga r;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public conAC.wsac.RecargaMonedero rm;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string WebSessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public conAC.wsac.Tarjeta t;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string cvv;
        
        public CargaVesta1aVezRequestBody() {
        }
        
        public CargaVesta1aVezRequestBody(conAC.wsac.Recarga r, conAC.wsac.RecargaMonedero rm, string WebSessionID, conAC.wsac.Tarjeta t, string cvv) {
            this.r = r;
            this.rm = rm;
            this.WebSessionID = WebSessionID;
            this.t = t;
            this.cvv = cvv;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CargaVesta1aVezResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CargaVesta1aVezResponse", Namespace="http://tempuri.org/", Order=0)]
        public conAC.wsac.CargaVesta1aVezResponseBody Body;
        
        public CargaVesta1aVezResponse() {
        }
        
        public CargaVesta1aVezResponse(conAC.wsac.CargaVesta1aVezResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CargaVesta1aVezResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CargaVesta1aVezResult;
        
        public CargaVesta1aVezResponseBody() {
        }
        
        public CargaVesta1aVezResponseBody(string CargaVesta1aVezResult) {
            this.CargaVesta1aVezResult = CargaVesta1aVezResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CargaVesta2aVezRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CargaVesta2aVez", Namespace="http://tempuri.org/", Order=0)]
        public conAC.wsac.CargaVesta2aVezRequestBody Body;
        
        public CargaVesta2aVezRequest() {
        }
        
        public CargaVesta2aVezRequest(conAC.wsac.CargaVesta2aVezRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CargaVesta2aVezRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public conAC.wsac.Recarga r;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public conAC.wsac.RecargaMonedero rm;
        
        public CargaVesta2aVezRequestBody() {
        }
        
        public CargaVesta2aVezRequestBody(conAC.wsac.Recarga r, conAC.wsac.RecargaMonedero rm) {
            this.r = r;
            this.rm = rm;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CargaVesta2aVezResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CargaVesta2aVezResponse", Namespace="http://tempuri.org/", Order=0)]
        public conAC.wsac.CargaVesta2aVezResponseBody Body;
        
        public CargaVesta2aVezResponse() {
        }
        
        public CargaVesta2aVezResponse(conAC.wsac.CargaVesta2aVezResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CargaVesta2aVezResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CargaVesta2aVezResult;
        
        public CargaVesta2aVezResponseBody() {
        }
        
        public CargaVesta2aVezResponseBody(string CargaVesta2aVezResult) {
            this.CargaVesta2aVezResult = CargaVesta2aVezResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IsacChannel : conAC.wsac.Isac, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsacClient : System.ServiceModel.ClientBase<conAC.wsac.Isac>, conAC.wsac.Isac {
        
        public IsacClient() {
        }
        
        public IsacClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IsacClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsacClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsacClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        conAC.wsac.GetCatalogoResponse conAC.wsac.Isac.GetCatalogo(conAC.wsac.GetCatalogoRequest request) {
            return base.Channel.GetCatalogo(request);
        }
        
        public string GetCatalogo(int idcatalogo, string where) {
            conAC.wsac.GetCatalogoRequest inValue = new conAC.wsac.GetCatalogoRequest();
            inValue.Body = new conAC.wsac.GetCatalogoRequestBody();
            inValue.Body.idcatalogo = idcatalogo;
            inValue.Body.where = where;
            conAC.wsac.GetCatalogoResponse retVal = ((conAC.wsac.Isac)(this)).GetCatalogo(inValue);
            return retVal.Body.GetCatalogoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<conAC.wsac.GetCatalogoResponse> conAC.wsac.Isac.GetCatalogoAsync(conAC.wsac.GetCatalogoRequest request) {
            return base.Channel.GetCatalogoAsync(request);
        }
        
        public System.Threading.Tasks.Task<conAC.wsac.GetCatalogoResponse> GetCatalogoAsync(int idcatalogo, string where) {
            conAC.wsac.GetCatalogoRequest inValue = new conAC.wsac.GetCatalogoRequest();
            inValue.Body = new conAC.wsac.GetCatalogoRequestBody();
            inValue.Body.idcatalogo = idcatalogo;
            inValue.Body.where = where;
            return ((conAC.wsac.Isac)(this)).GetCatalogoAsync(inValue);
        }
        
        public void EnviaMailRecordatorio(int idusuario) {
            base.Channel.EnviaMailRecordatorio(idusuario);
        }
        
        public System.Threading.Tasks.Task EnviaMailRecordatorioAsync(int idusuario) {
            return base.Channel.EnviaMailRecordatorioAsync(idusuario);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        conAC.wsac.AltaRecargaProgResponse conAC.wsac.Isac.AltaRecargaProg(conAC.wsac.AltaRecargaProgRequest request) {
            return base.Channel.AltaRecargaProg(request);
        }
        
        public int AltaRecargaProg(conAC.wsac.RecargaProg r) {
            conAC.wsac.AltaRecargaProgRequest inValue = new conAC.wsac.AltaRecargaProgRequest();
            inValue.Body = new conAC.wsac.AltaRecargaProgRequestBody();
            inValue.Body.r = r;
            conAC.wsac.AltaRecargaProgResponse retVal = ((conAC.wsac.Isac)(this)).AltaRecargaProg(inValue);
            return retVal.Body.AltaRecargaProgResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<conAC.wsac.AltaRecargaProgResponse> conAC.wsac.Isac.AltaRecargaProgAsync(conAC.wsac.AltaRecargaProgRequest request) {
            return base.Channel.AltaRecargaProgAsync(request);
        }
        
        public System.Threading.Tasks.Task<conAC.wsac.AltaRecargaProgResponse> AltaRecargaProgAsync(conAC.wsac.RecargaProg r) {
            conAC.wsac.AltaRecargaProgRequest inValue = new conAC.wsac.AltaRecargaProgRequest();
            inValue.Body = new conAC.wsac.AltaRecargaProgRequestBody();
            inValue.Body.r = r;
            return ((conAC.wsac.Isac)(this)).AltaRecargaProgAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        conAC.wsac.AltaRecargaResponse conAC.wsac.Isac.AltaRecarga(conAC.wsac.AltaRecargaRequest request) {
            return base.Channel.AltaRecarga(request);
        }
        
        public string AltaRecarga(conAC.wsac.Recarga r) {
            conAC.wsac.AltaRecargaRequest inValue = new conAC.wsac.AltaRecargaRequest();
            inValue.Body = new conAC.wsac.AltaRecargaRequestBody();
            inValue.Body.r = r;
            conAC.wsac.AltaRecargaResponse retVal = ((conAC.wsac.Isac)(this)).AltaRecarga(inValue);
            return retVal.Body.AltaRecargaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<conAC.wsac.AltaRecargaResponse> conAC.wsac.Isac.AltaRecargaAsync(conAC.wsac.AltaRecargaRequest request) {
            return base.Channel.AltaRecargaAsync(request);
        }
        
        public System.Threading.Tasks.Task<conAC.wsac.AltaRecargaResponse> AltaRecargaAsync(conAC.wsac.Recarga r) {
            conAC.wsac.AltaRecargaRequest inValue = new conAC.wsac.AltaRecargaRequest();
            inValue.Body = new conAC.wsac.AltaRecargaRequestBody();
            inValue.Body.r = r;
            return ((conAC.wsac.Isac)(this)).AltaRecargaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        conAC.wsac.AltaRecargaMonederoResponse conAC.wsac.Isac.AltaRecargaMonedero(conAC.wsac.AltaRecargaMonederoRequest request) {
            return base.Channel.AltaRecargaMonedero(request);
        }
        
        public string AltaRecargaMonedero(conAC.wsac.RecargaMonedero r) {
            conAC.wsac.AltaRecargaMonederoRequest inValue = new conAC.wsac.AltaRecargaMonederoRequest();
            inValue.Body = new conAC.wsac.AltaRecargaMonederoRequestBody();
            inValue.Body.r = r;
            conAC.wsac.AltaRecargaMonederoResponse retVal = ((conAC.wsac.Isac)(this)).AltaRecargaMonedero(inValue);
            return retVal.Body.AltaRecargaMonederoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<conAC.wsac.AltaRecargaMonederoResponse> conAC.wsac.Isac.AltaRecargaMonederoAsync(conAC.wsac.AltaRecargaMonederoRequest request) {
            return base.Channel.AltaRecargaMonederoAsync(request);
        }
        
        public System.Threading.Tasks.Task<conAC.wsac.AltaRecargaMonederoResponse> AltaRecargaMonederoAsync(conAC.wsac.RecargaMonedero r) {
            conAC.wsac.AltaRecargaMonederoRequest inValue = new conAC.wsac.AltaRecargaMonederoRequest();
            inValue.Body = new conAC.wsac.AltaRecargaMonederoRequestBody();
            inValue.Body.r = r;
            return ((conAC.wsac.Isac)(this)).AltaRecargaMonederoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        conAC.wsac.AltaRecargaViaWalletResponse conAC.wsac.Isac.AltaRecargaViaWallet(conAC.wsac.AltaRecargaViaWalletRequest request) {
            return base.Channel.AltaRecargaViaWallet(request);
        }
        
        public string AltaRecargaViaWallet(conAC.wsac.Recarga r) {
            conAC.wsac.AltaRecargaViaWalletRequest inValue = new conAC.wsac.AltaRecargaViaWalletRequest();
            inValue.Body = new conAC.wsac.AltaRecargaViaWalletRequestBody();
            inValue.Body.r = r;
            conAC.wsac.AltaRecargaViaWalletResponse retVal = ((conAC.wsac.Isac)(this)).AltaRecargaViaWallet(inValue);
            return retVal.Body.AltaRecargaViaWalletResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<conAC.wsac.AltaRecargaViaWalletResponse> conAC.wsac.Isac.AltaRecargaViaWalletAsync(conAC.wsac.AltaRecargaViaWalletRequest request) {
            return base.Channel.AltaRecargaViaWalletAsync(request);
        }
        
        public System.Threading.Tasks.Task<conAC.wsac.AltaRecargaViaWalletResponse> AltaRecargaViaWalletAsync(conAC.wsac.Recarga r) {
            conAC.wsac.AltaRecargaViaWalletRequest inValue = new conAC.wsac.AltaRecargaViaWalletRequest();
            inValue.Body = new conAC.wsac.AltaRecargaViaWalletRequestBody();
            inValue.Body.r = r;
            return ((conAC.wsac.Isac)(this)).AltaRecargaViaWalletAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        conAC.wsac.AltaUsrResponse conAC.wsac.Isac.AltaUsr(conAC.wsac.AltaUsrRequest request) {
            return base.Channel.AltaUsr(request);
        }
        
        public int AltaUsr(conAC.wsac.Usuario u) {
            conAC.wsac.AltaUsrRequest inValue = new conAC.wsac.AltaUsrRequest();
            inValue.Body = new conAC.wsac.AltaUsrRequestBody();
            inValue.Body.u = u;
            conAC.wsac.AltaUsrResponse retVal = ((conAC.wsac.Isac)(this)).AltaUsr(inValue);
            return retVal.Body.AltaUsrResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<conAC.wsac.AltaUsrResponse> conAC.wsac.Isac.AltaUsrAsync(conAC.wsac.AltaUsrRequest request) {
            return base.Channel.AltaUsrAsync(request);
        }
        
        public System.Threading.Tasks.Task<conAC.wsac.AltaUsrResponse> AltaUsrAsync(conAC.wsac.Usuario u) {
            conAC.wsac.AltaUsrRequest inValue = new conAC.wsac.AltaUsrRequest();
            inValue.Body = new conAC.wsac.AltaUsrRequestBody();
            inValue.Body.u = u;
            return ((conAC.wsac.Isac)(this)).AltaUsrAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        conAC.wsac.Mod_UsuarioResponse conAC.wsac.Isac.Mod_Usuario(conAC.wsac.Mod_UsuarioRequest request) {
            return base.Channel.Mod_Usuario(request);
        }
        
        public int Mod_Usuario(conAC.wsac.Usuario u) {
            conAC.wsac.Mod_UsuarioRequest inValue = new conAC.wsac.Mod_UsuarioRequest();
            inValue.Body = new conAC.wsac.Mod_UsuarioRequestBody();
            inValue.Body.u = u;
            conAC.wsac.Mod_UsuarioResponse retVal = ((conAC.wsac.Isac)(this)).Mod_Usuario(inValue);
            return retVal.Body.Mod_UsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<conAC.wsac.Mod_UsuarioResponse> conAC.wsac.Isac.Mod_UsuarioAsync(conAC.wsac.Mod_UsuarioRequest request) {
            return base.Channel.Mod_UsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<conAC.wsac.Mod_UsuarioResponse> Mod_UsuarioAsync(conAC.wsac.Usuario u) {
            conAC.wsac.Mod_UsuarioRequest inValue = new conAC.wsac.Mod_UsuarioRequest();
            inValue.Body = new conAC.wsac.Mod_UsuarioRequestBody();
            inValue.Body.u = u;
            return ((conAC.wsac.Isac)(this)).Mod_UsuarioAsync(inValue);
        }
        
        public bool EliminaTarjeta(int idtarjeta) {
            return base.Channel.EliminaTarjeta(idtarjeta);
        }
        
        public System.Threading.Tasks.Task<bool> EliminaTarjetaAsync(int idtarjeta) {
            return base.Channel.EliminaTarjetaAsync(idtarjeta);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        conAC.wsac.CargaVesta1aVezResponse conAC.wsac.Isac.CargaVesta1aVez(conAC.wsac.CargaVesta1aVezRequest request) {
            return base.Channel.CargaVesta1aVez(request);
        }
        
        public string CargaVesta1aVez(conAC.wsac.Recarga r, conAC.wsac.RecargaMonedero rm, string WebSessionID, conAC.wsac.Tarjeta t, string cvv) {
            conAC.wsac.CargaVesta1aVezRequest inValue = new conAC.wsac.CargaVesta1aVezRequest();
            inValue.Body = new conAC.wsac.CargaVesta1aVezRequestBody();
            inValue.Body.r = r;
            inValue.Body.rm = rm;
            inValue.Body.WebSessionID = WebSessionID;
            inValue.Body.t = t;
            inValue.Body.cvv = cvv;
            conAC.wsac.CargaVesta1aVezResponse retVal = ((conAC.wsac.Isac)(this)).CargaVesta1aVez(inValue);
            return retVal.Body.CargaVesta1aVezResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<conAC.wsac.CargaVesta1aVezResponse> conAC.wsac.Isac.CargaVesta1aVezAsync(conAC.wsac.CargaVesta1aVezRequest request) {
            return base.Channel.CargaVesta1aVezAsync(request);
        }
        
        public System.Threading.Tasks.Task<conAC.wsac.CargaVesta1aVezResponse> CargaVesta1aVezAsync(conAC.wsac.Recarga r, conAC.wsac.RecargaMonedero rm, string WebSessionID, conAC.wsac.Tarjeta t, string cvv) {
            conAC.wsac.CargaVesta1aVezRequest inValue = new conAC.wsac.CargaVesta1aVezRequest();
            inValue.Body = new conAC.wsac.CargaVesta1aVezRequestBody();
            inValue.Body.r = r;
            inValue.Body.rm = rm;
            inValue.Body.WebSessionID = WebSessionID;
            inValue.Body.t = t;
            inValue.Body.cvv = cvv;
            return ((conAC.wsac.Isac)(this)).CargaVesta1aVezAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        conAC.wsac.CargaVesta2aVezResponse conAC.wsac.Isac.CargaVesta2aVez(conAC.wsac.CargaVesta2aVezRequest request) {
            return base.Channel.CargaVesta2aVez(request);
        }
        
        public string CargaVesta2aVez(conAC.wsac.Recarga r, conAC.wsac.RecargaMonedero rm) {
            conAC.wsac.CargaVesta2aVezRequest inValue = new conAC.wsac.CargaVesta2aVezRequest();
            inValue.Body = new conAC.wsac.CargaVesta2aVezRequestBody();
            inValue.Body.r = r;
            inValue.Body.rm = rm;
            conAC.wsac.CargaVesta2aVezResponse retVal = ((conAC.wsac.Isac)(this)).CargaVesta2aVez(inValue);
            return retVal.Body.CargaVesta2aVezResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<conAC.wsac.CargaVesta2aVezResponse> conAC.wsac.Isac.CargaVesta2aVezAsync(conAC.wsac.CargaVesta2aVezRequest request) {
            return base.Channel.CargaVesta2aVezAsync(request);
        }
        
        public System.Threading.Tasks.Task<conAC.wsac.CargaVesta2aVezResponse> CargaVesta2aVezAsync(conAC.wsac.Recarga r, conAC.wsac.RecargaMonedero rm) {
            conAC.wsac.CargaVesta2aVezRequest inValue = new conAC.wsac.CargaVesta2aVezRequest();
            inValue.Body = new conAC.wsac.CargaVesta2aVezRequestBody();
            inValue.Body.r = r;
            inValue.Body.rm = rm;
            return ((conAC.wsac.Isac)(this)).CargaVesta2aVezAsync(inValue);
        }
    }
}
