// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MasTicket.wscatalogos {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.0.1.24")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wscatalogosSoap", Namespace="http://tempuri.org/")]
    public partial class wscatalogos : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetMontoMaxOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMonederoHabOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAdminOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCatalogoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCodigoReferidoUsrOperationCompleted;
        
        /// CodeRemarks
        public wscatalogos() {
            this.Url = "https://asicompras.com/wsac/wscatalogos.asmx";
        }
        
        public wscatalogos(string url) {
            this.Url = url;
        }
        
        /// CodeRemarks
        public event GetMontoMaxCompletedEventHandler GetMontoMaxCompleted;
        
        /// CodeRemarks
        public event GetMonederoHabCompletedEventHandler GetMonederoHabCompleted;
        
        /// CodeRemarks
        public event GetAdminCompletedEventHandler GetAdminCompleted;
        
        /// CodeRemarks
        public event GetUserCompletedEventHandler GetUserCompleted;
        
        /// CodeRemarks
        public event GetCatalogoCompletedEventHandler GetCatalogoCompleted;
        
        /// CodeRemarks
        public event GetCodigoReferidoUsrCompletedEventHandler GetCodigoReferidoUsrCompleted;
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMontoMax", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public decimal GetMontoMax() {
            object[] results = this.Invoke("GetMontoMax", new object[0]);
            return ((decimal)(results[0]));
        }
        
        /// CodeRemarks
        public void GetMontoMaxAsync() {
            this.GetMontoMaxAsync(null);
        }
        
        /// CodeRemarks
        public void GetMontoMaxAsync(object userState) {
            if ((this.GetMontoMaxOperationCompleted == null)) {
                this.GetMontoMaxOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMontoMaxOperationCompleted);
            }
            this.InvokeAsync("GetMontoMax", new object[0], this.GetMontoMaxOperationCompleted, userState);
        }
        
        private void OnGetMontoMaxOperationCompleted(object arg) {
            if ((this.GetMontoMaxCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMontoMaxCompleted(this, new GetMontoMaxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMonederoHab", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetMonederoHab() {
            object[] results = this.Invoke("GetMonederoHab", new object[0]);
            return ((int)(results[0]));
        }
        
        /// CodeRemarks
        public void GetMonederoHabAsync() {
            this.GetMonederoHabAsync(null);
        }
        
        /// CodeRemarks
        public void GetMonederoHabAsync(object userState) {
            if ((this.GetMonederoHabOperationCompleted == null)) {
                this.GetMonederoHabOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMonederoHabOperationCompleted);
            }
            this.InvokeAsync("GetMonederoHab", new object[0], this.GetMonederoHabOperationCompleted, userState);
        }
        
        private void OnGetMonederoHabOperationCompleted(object arg) {
            if ((this.GetMonederoHabCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMonederoHabCompleted(this, new GetMonederoHabCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAdmin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAdmin(int idusr, string email, string nip) {
            object[] results = this.Invoke("GetAdmin", new object[] {
                        idusr,
                        email,
                        nip});
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public void GetAdminAsync(int idusr, string email, string nip) {
            this.GetAdminAsync(idusr, email, nip, null);
        }
        
        /// CodeRemarks
        public void GetAdminAsync(int idusr, string email, string nip, object userState) {
            if ((this.GetAdminOperationCompleted == null)) {
                this.GetAdminOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAdminOperationCompleted);
            }
            this.InvokeAsync("GetAdmin", new object[] {
                        idusr,
                        email,
                        nip}, this.GetAdminOperationCompleted, userState);
        }
        
        private void OnGetAdminOperationCompleted(object arg) {
            if ((this.GetAdminCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAdminCompleted(this, new GetAdminCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUser(int idusr, string email, string nip) {
            object[] results = this.Invoke("GetUser", new object[] {
                        idusr,
                        email,
                        nip});
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public void GetUserAsync(int idusr, string email, string nip) {
            this.GetUserAsync(idusr, email, nip, null);
        }
        
        /// CodeRemarks
        public void GetUserAsync(int idusr, string email, string nip, object userState) {
            if ((this.GetUserOperationCompleted == null)) {
                this.GetUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserOperationCompleted);
            }
            this.InvokeAsync("GetUser", new object[] {
                        idusr,
                        email,
                        nip}, this.GetUserOperationCompleted, userState);
        }
        
        private void OnGetUserOperationCompleted(object arg) {
            if ((this.GetUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserCompleted(this, new GetUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCatalogo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCatalogo(int idcatalogo, string @where) {
            object[] results = this.Invoke("GetCatalogo", new object[] {
                        idcatalogo,
                        @where});
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public void GetCatalogoAsync(int idcatalogo, string @where) {
            this.GetCatalogoAsync(idcatalogo, @where, null);
        }
        
        /// CodeRemarks
        public void GetCatalogoAsync(int idcatalogo, string @where, object userState) {
            if ((this.GetCatalogoOperationCompleted == null)) {
                this.GetCatalogoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCatalogoOperationCompleted);
            }
            this.InvokeAsync("GetCatalogo", new object[] {
                        idcatalogo,
                        @where}, this.GetCatalogoOperationCompleted, userState);
        }
        
        private void OnGetCatalogoOperationCompleted(object arg) {
            if ((this.GetCatalogoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCatalogoCompleted(this, new GetCatalogoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCodigoReferidoUsr", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCodigoReferidoUsr(int idusr) {
            object[] results = this.Invoke("GetCodigoReferidoUsr", new object[] {
                        idusr});
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public void GetCodigoReferidoUsrAsync(int idusr) {
            this.GetCodigoReferidoUsrAsync(idusr, null);
        }
        
        /// CodeRemarks
        public void GetCodigoReferidoUsrAsync(int idusr, object userState) {
            if ((this.GetCodigoReferidoUsrOperationCompleted == null)) {
                this.GetCodigoReferidoUsrOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCodigoReferidoUsrOperationCompleted);
            }
            this.InvokeAsync("GetCodigoReferidoUsr", new object[] {
                        idusr}, this.GetCodigoReferidoUsrOperationCompleted, userState);
        }
        
        private void OnGetCodigoReferidoUsrOperationCompleted(object arg) {
            if ((this.GetCodigoReferidoUsrCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCodigoReferidoUsrCompleted(this, new GetCodigoReferidoUsrCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.0.1.24")]
    public delegate void GetMontoMaxCompletedEventHandler(object sender, GetMontoMaxCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.0.1.24")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMontoMaxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMontoMaxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public decimal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.0.1.24")]
    public delegate void GetMonederoHabCompletedEventHandler(object sender, GetMonederoHabCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.0.1.24")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMonederoHabCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMonederoHabCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.0.1.24")]
    public delegate void GetAdminCompletedEventHandler(object sender, GetAdminCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.0.1.24")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAdminCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAdminCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.0.1.24")]
    public delegate void GetUserCompletedEventHandler(object sender, GetUserCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.0.1.24")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.0.1.24")]
    public delegate void GetCatalogoCompletedEventHandler(object sender, GetCatalogoCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.0.1.24")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCatalogoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCatalogoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.0.1.24")]
    public delegate void GetCodigoReferidoUsrCompletedEventHandler(object sender, GetCodigoReferidoUsrCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.0.1.24")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCodigoReferidoUsrCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCodigoReferidoUsrCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
