#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("CaveBirdLabs.Forms.Platform.Android.Resource", IsApplication=false)]

namespace CaveBirdLabs.Forms.Platform.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public static int centered = 2130771969;
			
			// aapt resource value: 0x7f01000c
			public static int clipPadding = 2130771980;
			
			// aapt resource value: 0x7f010018
			public static int fadeDelay = 2130771992;
			
			// aapt resource value: 0x7f010019
			public static int fadeLength = 2130771993;
			
			// aapt resource value: 0x7f010017
			public static int fades = 2130771991;
			
			// aapt resource value: 0x7f010005
			public static int fillColor = 2130771973;
			
			// aapt resource value: 0x7f01000d
			public static int footerColor = 2130771981;
			
			// aapt resource value: 0x7f010010
			public static int footerIndicatorHeight = 2130771984;
			
			// aapt resource value: 0x7f01000f
			public static int footerIndicatorStyle = 2130771983;
			
			// aapt resource value: 0x7f010011
			public static int footerIndicatorUnderlinePadding = 2130771985;
			
			// aapt resource value: 0x7f01000e
			public static int footerLineHeight = 2130771982;
			
			// aapt resource value: 0x7f010012
			public static int footerPadding = 2130771986;
			
			// aapt resource value: 0x7f01000b
			public static int gapWidth = 2130771979;
			
			// aapt resource value: 0x7f010013
			public static int linePosition = 2130771987;
			
			// aapt resource value: 0x7f01000a
			public static int lineWidth = 2130771978;
			
			// aapt resource value: 0x7f010006
			public static int pageColor = 2130771974;
			
			// aapt resource value: 0x7f010007
			public static int radius = 2130771975;
			
			// aapt resource value: 0x7f010014
			public static int selectedBold = 2130771988;
			
			// aapt resource value: 0x7f010002
			public static int selectedColor = 2130771970;
			
			// aapt resource value: 0x7f010008
			public static int snap = 2130771976;
			
			// aapt resource value: 0x7f010009
			public static int strokeColor = 2130771977;
			
			// aapt resource value: 0x7f010003
			public static int strokeWidth = 2130771971;
			
			// aapt resource value: 0x7f010015
			public static int titlePadding = 2130771989;
			
			// aapt resource value: 0x7f010016
			public static int topPadding = 2130771990;
			
			// aapt resource value: 0x7f010004
			public static int unselectedColor = 2130771972;
			
			// aapt resource value: 0x7f010000
			public static int vpiCirclePageIndicatorStyle = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f030000
			public static int default_circle_indicator_centered = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int default_circle_indicator_snap = 2130903041;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public static int default_circle_indicator_fill_color = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int default_circle_indicator_page_color = 2130968577;
			
			// aapt resource value: 0x7f040002
			public static int default_circle_indicator_stroke_color = 2130968578;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public static int default_circle_indicator_radius = 2131099648;
			
			// aapt resource value: 0x7f060001
			public static int default_circle_indicator_stroke_width = 2131099649;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070003
			public static int bottom = 2131165187;
			
			// aapt resource value: 0x7f070000
			public static int none = 2131165184;
			
			// aapt resource value: 0x7f070004
			public static int top = 2131165188;
			
			// aapt resource value: 0x7f070001
			public static int triangle = 2131165185;
			
			// aapt resource value: 0x7f070002
			public static int underline = 2131165186;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050000
			public static int default_circle_indicator_orientation = 2131034112;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f020000
			public static int library_name = 2130837504;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CirclePageIndicator = new int[]
			{
					16842948,
					16842964,
					2130771969,
					2130771971,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977};
			
			// aapt resource value: 1
			public static int CirclePageIndicator_android_background = 1;
			
			// aapt resource value: 0
			public static int CirclePageIndicator_android_orientation = 0;
			
			// aapt resource value: 2
			public static int CirclePageIndicator_centered = 2;
			
			// aapt resource value: 4
			public static int CirclePageIndicator_fillColor = 4;
			
			// aapt resource value: 5
			public static int CirclePageIndicator_pageColor = 5;
			
			// aapt resource value: 6
			public static int CirclePageIndicator_radius = 6;
			
			// aapt resource value: 7
			public static int CirclePageIndicator_snap = 7;
			
			// aapt resource value: 8
			public static int CirclePageIndicator_strokeColor = 8;
			
			// aapt resource value: 3
			public static int CirclePageIndicator_strokeWidth = 3;
			
			public static int[] LinePageIndicator = new int[]
			{
					16842964,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771978,
					2130771979};
			
			// aapt resource value: 0
			public static int LinePageIndicator_android_background = 0;
			
			// aapt resource value: 1
			public static int LinePageIndicator_centered = 1;
			
			// aapt resource value: 6
			public static int LinePageIndicator_gapWidth = 6;
			
			// aapt resource value: 5
			public static int LinePageIndicator_lineWidth = 5;
			
			// aapt resource value: 2
			public static int LinePageIndicator_selectedColor = 2;
			
			// aapt resource value: 3
			public static int LinePageIndicator_strokeWidth = 3;
			
			// aapt resource value: 4
			public static int LinePageIndicator_unselectedColor = 4;
			
			public static int[] TitlePageIndicator = new int[]
			{
					16842901,
					16842904,
					16842964,
					2130771970,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 2
			public static int TitlePageIndicator_android_background = 2;
			
			// aapt resource value: 1
			public static int TitlePageIndicator_android_textColor = 1;
			
			// aapt resource value: 0
			public static int TitlePageIndicator_android_textSize = 0;
			
			// aapt resource value: 4
			public static int TitlePageIndicator_clipPadding = 4;
			
			// aapt resource value: 5
			public static int TitlePageIndicator_footerColor = 5;
			
			// aapt resource value: 8
			public static int TitlePageIndicator_footerIndicatorHeight = 8;
			
			// aapt resource value: 7
			public static int TitlePageIndicator_footerIndicatorStyle = 7;
			
			// aapt resource value: 9
			public static int TitlePageIndicator_footerIndicatorUnderlinePadding = 9;
			
			// aapt resource value: 6
			public static int TitlePageIndicator_footerLineHeight = 6;
			
			// aapt resource value: 10
			public static int TitlePageIndicator_footerPadding = 10;
			
			// aapt resource value: 11
			public static int TitlePageIndicator_linePosition = 11;
			
			// aapt resource value: 12
			public static int TitlePageIndicator_selectedBold = 12;
			
			// aapt resource value: 3
			public static int TitlePageIndicator_selectedColor = 3;
			
			// aapt resource value: 13
			public static int TitlePageIndicator_titlePadding = 13;
			
			// aapt resource value: 14
			public static int TitlePageIndicator_topPadding = 14;
			
			public static int[] UnderlinePageIndicator = new int[]
			{
					16842964,
					2130771970,
					2130771991,
					2130771992,
					2130771993};
			
			// aapt resource value: 0
			public static int UnderlinePageIndicator_android_background = 0;
			
			// aapt resource value: 3
			public static int UnderlinePageIndicator_fadeDelay = 3;
			
			// aapt resource value: 4
			public static int UnderlinePageIndicator_fadeLength = 4;
			
			// aapt resource value: 2
			public static int UnderlinePageIndicator_fades = 2;
			
			// aapt resource value: 1
			public static int UnderlinePageIndicator_selectedColor = 1;
			
			public static int[] ViewPagerIndicator = new int[]
			{
					2130771968};
			
			// aapt resource value: 0
			public static int ViewPagerIndicator_vpiCirclePageIndicatorStyle = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
